/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      "colors": {
        "on-secondary": "#283500",
        "secondary-fixed": "#c3f400",
        "on-secondary-container": "#556d00",
        "surface-container-highest": "#32343f",
        "surface-tint": "#b6c4ff",
        "on-tertiary-fixed": "#320047",
        "error-container": "#93000a",
        "on-tertiary-container": "#fadeff",
        "surface-container-lowest": "#0c0e17",
        "primary-fixed": "#dce1ff",
        "inverse-on-surface": "#2e303a",
        "secondary-container": "#c3f400",
        "inverse-surface": "#e1e1ef",
        "on-error": "#690005",
        "on-surface": "#e1e1ef",
        "outline-variant": "#434656",
        "surface-variant": "#32343f",
        "on-primary": "#002780",
        "inverse-primary": "#004dea",
        "surface-container-high": "#282933",
        "on-primary-container": "#e3e6ff",
        "tertiary-fixed": "#f8d8ff",
        "secondary-fixed-dim": "#abd600",
        "on-primary-fixed": "#001551",
        "on-background": "#e1e1ef",
        "secondary": "#ffffff",
        "primary": "#b6c4ff",
        "background": "#11131c",
        "on-primary-fixed-variant": "#0039b3",
        "surface-container-low": "#191b25",
        "surface-dim": "#11131c",
        "surface": "#11131c",
        "primary-container": "#0055ff",
        "on-tertiary": "#520071",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#161e00",
        "outline": "#8d90a2",
        "tertiary": "#ecb2ff",
        "tertiary-fixed-dim": "#ecb2ff",
        "surface-container": "#1d1f29",
        "tertiary-container": "#a700e2",
        "on-secondary-fixed-variant": "#3c4d00",
        "on-surface-variant": "#c3c5d9",
        "primary-fixed-dim": "#b6c4ff",
        "surface-bright": "#373943",
        "on-tertiary-fixed-variant": "#74009f",
        "on-error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "8px",
        "gutter": "16px",
        "lg": "24px",
        "margin-safe": "20px",
        "xl": "32px",
        "md": "16px",
        "unit": "4px",
        "xs": "4px"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "display-xl": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Space Grotesk"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", {"lineHeight": "1.5", "fontWeight": "600"}],
        "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-md": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
};
